version: "3.8"

services:
  line-provider:
    build: ./line-provider
    container_name: line-provider
    command: "uvicorn app:app --host 0.0.0.0 --port 8080"
    ports:
      - "8080:8080"
    depends_on:
      - rabbit
    restart: always
    networks:
      - bs_network

  bet-maker:
    build: ./bet-maker
    container_name: bet-maker
    command: "uvicorn app.main:app --host 0.0.0.0 --port 8081"
    env_file:
      - bet_maker/.env
    volumes:
      - ./bet-maker/:/code
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - rabbit
    restart: always
    networks:
      - bs_network

  postgres:
    image: postgres:17-alpine
    restart: always
    env_file:
      - bet_maker/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - bs_network

  rabbit:
    image: rabbitmq:4.0.2-alpine
    hostname: rabbitmq
    restart: always
    env_file:
      - line_provider/.env
    environment:
      - RABBITMQ_DEFAULT_USER=&{R}
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    ports:
      - "15672:15672"
    networks:
      - bs_network

volumes:
  postgres_data:
networks:
  bs_network: