services:
  line-provider:
    build:
      context: line_provider
      dockerfile: settings/Dockerfile
    container_name: line-provider
    command: "uvicorn main:app --host 0.0.0.0 --port 8080"
    ports:
      - "8080:8080"
    depends_on:
      - rabbit
    restart: always

  bet-maker:
    build:
      context: bet_maker
      dockerfile: settings/Dockerfile
    container_name: bet-maker
    entrypoint: >
      sh -c
        "
          echo Running tests...
          pytest -v
          echo Applying alembic migration...
          alembic -c settings/alembic.ini upgrade head
          echo Starting uvicorn server...
          uvicorn main:app --host 0.0.0.0 --port 8081
          done
        "
    env_file:
      - bet_maker/settings/.env
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - rabbit
    restart: always

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - bet_maker/settings/.env

  rabbit:
    image: rabbitmq:4.0.2-alpine
    container_name: rabbit
    restart: always
    env_file:
      - line_provider/settings/.env
    ports:
      - "5672:5672"
