services:
  line-provider:
    build:
      context: line_provider
    container_name: line-provider
    command: "uvicorn main:app --host 0.0.0.0 --port 8080"
    ports:
      - "8080:8080"
    depends_on:
      - rabbit
    restart: always

  bet-maker:
    build:
      context: bet_maker
    container_name: bet-maker
    entrypoint: >
      sh -c
        "
          sleep 10
          echo Stairway testing
          alembic upgrade head
          alembic downgrade -1
          echo Applying alembic migration...
          alembic upgrade head
          echo Starting uvicorn server...
          uvicorn main:app --host 0.0.0.0 --port 8081
          done
        "
    env_file:
      - bet_maker/.env
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - rabbit
    restart: always

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - bet_maker/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=&{POSTGRES_USER}
      - POSTGRES_PASSWORD=&{POSTGRES_PASSWORD}
      - POSTGRES_DB=&{POSTGRES_DB}

  rabbit:
    image: rabbitmq:4.0.2-alpine
    container_name: rabbit
    restart: always
    env_file:
      - line_provider/.env
    environment:
      - RABBITMQ_DEFAULT_USER=&{RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=&{RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"

volumes:
  postgres_data:
